spring:
  application:
    name: orders
  datasource:
    url: jdbc:postgresql://localhost:5555/istoreorders
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8084

istore:
  orders:
    clients:
      products:
        url: http://localhost:8082/products
      clients:
        url: http://localhost:8083/clients
  config:
    kafka:
      server-url: http://localhost:29092
      topics:
        order-paid: istore.orders-paid
        order-made: istore.orders-made
        order-send: istore.orders-send